<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>quarkus-jdbc-postgresql-parent</artifactId>
        <groupId>io.quarkus</groupId>
        <version>3.21.4</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>quarkus-jdbc-postgresql</artifactId>
    <version>3.21.4-lineaje-01</version>
    <name>Quarkus - JDBC - PostgreSQL - Runtime</name>
    <description>Connect to the PostgreSQL database via JDBC</description>
    <properties>
        <compiler-plugin.version>${version.compiler.plugin}</compiler-plugin.version>
        <kotlin.version>2.0.21</kotlin.version>
        <dokka.version>2.0.0</dokka.version>
        <scala.version>2.13.12</scala.version>
        <scala-maven-plugin.version>4.9.2</scala-maven-plugin.version>
        <scala-plugin.version>${scala-maven-plugin.version}</scala-plugin.version>
        <jboss-bridger-plugin.version>1.6.Final</jboss-bridger-plugin.version>
        <jandex.version>3.3.0</jandex.version>
        <jandex-gradle-plugin.version>1.0.0</jandex-gradle-plugin.version>
        <asciidoctorj.version>2.5.13</asciidoctorj.version>
        <htmlunit.version>4.10.0</htmlunit.version>
        <javaparser-core.version>3.26.3</javaparser-core.version>
        <jdeparser.version>2.0.3.Final</jdeparser.version>
        <subethasmtp.version>6.0.1</subethasmtp.version>
        <freemarker.version>2.3.34</freemarker.version>
        <commonmark.version>0.24.0</commonmark.version>
        <jgit.version>7.2.0.202503040940-r</jgit.version>
        <arquillian.version>1.7.0.Final</arquillian.version>
        <m2e.apt.activation>jdt_apt</m2e.apt.activation>
        <minimum-java-version>${maven.compiler.release}</minimum-java-version>
        <recommended-java-version>21</recommended-java-version>
        <supported-maven-versions>[3.8.6,)</supported-maven-versions>
        <proposed-maven-version>3.9.9</proposed-maven-version>
        <maven-wrapper.version>3.3.2</maven-wrapper.version>
        <gradle-wrapper.version>8.13</gradle-wrapper.version>
        <quarkus-gradle-plugin.version>3.21.4</quarkus-gradle-plugin.version>
        <quarkus-maven-plugin.version>3.21.4</quarkus-maven-plugin.version>
        <maven-plugin-plugin.version>3.8.1</maven-plugin-plugin.version>
        <volume.access.modifier>:Z</volume.access.modifier>
        <elasticsearch-server.version>8.15.0</elasticsearch-server.version>
        <elasticsearch.image>docker.io/elastic/elasticsearch:${elasticsearch-server.version}</elasticsearch.image>
        <logstash.image>docker.io/elastic/logstash:${elasticsearch-server.version}</logstash.image>
        <kibana.image>docker.io/elastic/kibana:${elasticsearch-server.version}</kibana.image>
        <elasticsearch.protocol>http</elasticsearch.protocol>
        <opensearch-server.version>2.16.0</opensearch-server.version>
        <opensearch.image>docker.io/opensearchproject/opensearch:${opensearch-server.version}</opensearch.image>
        <opensearch.protocol>http</opensearch.protocol>
        <junit-pioneer.version>2.2.0</junit-pioneer.version>
        <postgres.image>docker.io/postgres:17</postgres.image>
        <mariadb.image>docker.io/mariadb:10.11</mariadb.image>
        <db2.image>icr.io/db2_community/db2:12.1.0.0</db2.image>
        <mssql.image>mcr.microsoft.com/mssql/server:2022-latest</mssql.image>
        <mysql.image>docker.io/mysql:8.4</mysql.image>
        <oracle.image>docker.io/gvenzl/oracle-free:23-slim-faststart</oracle.image>
        <mongo.image>docker.io/mongo:7.0</mongo.image>
        <junit4.version>4.13.2</junit4.version>
        <keycloak.server.version>26.1.3</keycloak.server.version>
        <keycloak.wildfly.version>19.0.3</keycloak.wildfly.version>
        <keycloak.docker.image>quay.io/keycloak/keycloak:${keycloak.server.version}</keycloak.docker.image>
        <keycloak.docker.legacy.image>quay.io/keycloak/keycloak:${keycloak.wildfly.version}-legacy</keycloak.docker.legacy.image>
        <unboundid-ldap.version>7.0.2</unboundid-ldap.version>
        <assertj.version>3.27.3</assertj.version>
        <wiremock.version>3.12.1</wiremock.version>
        <wiremock-maven-plugin.version>7.3.0</wiremock-maven-plugin.version>
        <artemis.version>2.39.0</artemis.version>
        <asciidoctor-maven-plugin.version>2.0.0</asciidoctor-maven-plugin.version>
        <docker-maven-plugin.version>0.45.1</docker-maven-plugin.version>
        <maven-invoker-plugin.version>3.9.0</maven-invoker-plugin.version>
        <revapi-maven-plugin.version>0.14.7</revapi-maven-plugin.version>
        <revapi-java-plugin.version>0.26.1</revapi-java-plugin.version>
        <build-helper-plugin.version>3.6.0</build-helper-plugin.version>
        <revapi-reporter-text.version>0.14.5</revapi-reporter-text.version>
        <revapi-reporter-json.version>0.4.5</revapi-reporter-json.version>
        <revapi.oldVersion>1.6.0.Final</revapi.oldVersion>
        <revapi.newVersion>3.21.4</revapi.newVersion>
        <revapi.reportSeverity>nonBreaking</revapi.reportSeverity>
        <revapi.skip>true</revapi.skip>
        <revapi.checkdeps>true</revapi.checkdeps>
        <revapi.buildFailureMessage>Run "jbang revapi-update" to update api-changes.xml file and also add the justification for those changes in that file.</revapi.buildFailureMessage>
        <forbiddenapis-maven-plugin.version>3.4</forbiddenapis-maven-plugin.version>
        <platform.quarkus.native.builder-image>mandrel</platform.quarkus.native.builder-image>
        <script.extension>sh</script.extension>
        <docker-prune.location>${maven.multiModuleProjectDirectory}/.github/docker-prune.${script.extension}</docker-prune.location>
        <failsafe.argLine.additional>${surefire.argLine.additional}</failsafe.argLine.additional>
        <gcf-invoker.version>1.4.1</gcf-invoker.version>
        <jakarta.jms-api.version>3.1.0</jakarta.jms-api.version>
        <properties-maven-plugin.version>1.1.0</properties-maven-plugin.version>
        <quarkus.analytics.disabled>true</quarkus.analytics.disabled>
        <develocity.pts.enabled>false</develocity.pts.enabled>
        <develocity.pts.active>false</develocity.pts.active>
        <graalvmHome>${env.GRAALVM_HOME}</graalvmHome>
        <postgres.url>jdbc:postgresql:hibernate_orm_test</postgres.url>
        <gitflow-incremental-builder.version>4.5.4</gitflow-incremental-builder.version>
        <quarkus-platform-bom-plugin.version>0.0.119</quarkus-platform-bom-plugin.version>
        <skipDocs>false</skipDocs>
        <skip.gradle.tests>false</skip.gradle.tests>
        <maven-enforcer-plugin.phase>validate</maven-enforcer-plugin.phase>
        <forbiddenapis-maven-plugin.phase>verify</forbiddenapis-maven-plugin.phase>
        <owasp-dependency-check-plugin.version>11.1.0</owasp-dependency-check-plugin.version>
        <jacoco.version>0.8.13</jacoco.version>
        <kubernetes-client.version>7.1.0</kubernetes-client.version>
        <rest-assured.version>5.5.1</rest-assured.version>
        <hibernate-orm.version>6.6.13.Final</hibernate-orm.version>
        <antlr.version>4.13.0</antlr.version>
        <bytebuddy.version>1.15.11</bytebuddy.version>
        <hibernate-commons-annotations.version>7.0.3.Final</hibernate-commons-annotations.version>
        <hibernate-reactive.version>2.4.6.Final</hibernate-reactive.version>
        <hibernate-validator.version>8.0.2.Final</hibernate-validator.version>
        <hibernate-search.version>7.2.3.Final</hibernate-search.version>
        <grpc.version>1.69.1</grpc.version>
        <grpc-jprotoc.version>1.2.2</grpc-jprotoc.version>
        <protoc.version>3.25.5</protoc.version>
        <protobuf-java.version>${protoc.version}</protobuf-java.version>
        <protobuf-kotlin.version>4.29.3</protobuf-kotlin.version>
        <proto-google-common-protos.version>2.53.0</proto-google-common-protos.version>
        <smallrye-certificate-generator.version>0.9.2</smallrye-certificate-generator.version>
        <testng.version>7.8.0</testng.version>
        <version.archetype.plugin>3.3.0</version.archetype.plugin>
        <version.buildhelper.plugin>3.6.0</version.buildhelper.plugin>
        <version.buildnumber.plugin>3.0.0</version.buildnumber.plugin>
        <version.clean.plugin>3.2.0</version.clean.plugin>
        <version.compiler.plugin>3.14.0</version.compiler.plugin>
        <version.deploy.plugin>3.1.1</version.deploy.plugin>
        <version.plugin.plugin>3.11.0</version.plugin.plugin>
        <version.dependency.plugin>3.6.1</version.dependency.plugin>
        <version.enforcer.plugin>3.3.0</version.enforcer.plugin>
        <version.exec.plugin>3.5.0</version.exec.plugin>
        <version.formatter.plugin>2.25.0</version.formatter.plugin>
        <version.gpg.plugin>3.0.1</version.gpg.plugin>
        <version.impsort.plugin>1.12.0</version.impsort.plugin>
        <version.install.plugin>3.1.1</version.install.plugin>
        <version.javadoc.plugin>3.5.0</version.javadoc.plugin>
        <version.jar.plugin>3.3.0</version.jar.plugin>
        <version.nexus-staging.plugin>1.6.13</version.nexus-staging.plugin>
        <version.release.plugin>3.0.0</version.release.plugin>
        <version.resources.plugin>3.3.1</version.resources.plugin>
        <version.shade.plugin>3.2.1</version.shade.plugin>
        <version.source.plugin>3.2.1</version.source.plugin>
        <version.surefire.plugin>3.5.2</version.surefire.plugin>
        <version.failsafe.plugin>${version.surefire.plugin}</version.failsafe.plugin>
        <version.versions.plugin>2.15.0</version.versions.plugin>
        <version.yaml-properties.plugin>1.1.3</version.yaml-properties.plugin>
        <format.skip>false</format.skip>
        <maven.compiler.parameters>true</maven.compiler.parameters>
        <maven.compiler.source>${maven.compiler.release}</maven.compiler.source>
        <maven.compiler.target>${maven.compiler.release}</maven.compiler.target>
        <maven.compiler.release>17</maven.compiler.release>
        <maven.compiler.testTarget>${maven.compiler.target}</maven.compiler.testTarget>
        <maven.compiler.testSource>${maven.compiler.source}</maven.compiler.testSource>
        <maven.javadoc.failOnError>false</maven.javadoc.failOnError>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <project.build.outputTimestamp>2025-04-23T12:30:32Z</project.build.outputTimestamp>
        <maven.compiler.argument.target>${maven.compiler.target}</maven.compiler.argument.target>
        <maven.compiler.argument.source>${maven.compiler.source}</maven.compiler.argument.source>
        <maven.compiler.argument.testTarget>${maven.compiler.testTarget}</maven.compiler.argument.testTarget>
        <maven.compiler.argument.testSource>${maven.compiler.testSource}</maven.compiler.argument.testSource>
        <maven.min.version>3.9.6</maven.min.version>
        <jdk.min.version>${maven.compiler.argument.source}</jdk.min.version>
        <insecure.repositories>ERROR</insecure.repositories>
        <useReleaseProfile>false</useReleaseProfile>
    </properties>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.quarkus</groupId>
                <artifactId>quarkus-bom</artifactId>
                <version>3.21.4</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>


    <dependencies>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-arc</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-agroal</artifactId>
        </dependency>
        
        <dependency>
            <groupId>org.graalvm.sdk</groupId>
            <artifactId>nativeimage</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-kubernetes-service-binding</artifactId>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-flyway-postgresql</artifactId>
            <optional>true</optional>  <!-- conditional dependency -->
        </dependency>

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-junit5-internal</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <scope>test</scope>
        </dependency>
    <dependency>
      <groupId>org.postgresql</groupId>
      <artifactId>postgresql</artifactId>
      <version>42.7.11</version>
    </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>io.quarkus</groupId>
                <artifactId>quarkus-extension-maven-plugin</artifactId>
                <configuration>
                    <parentFirstArtifacts>
                        <parentFirstArtifact>org.postgresql:postgresql</parentFirstArtifact>
                    </parentFirstArtifacts>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <executions>
                    <execution>
                        <id>default-compile</id>
                        <configuration>
                            <annotationProcessorPaths>
                                <path>
                                    <groupId>io.quarkus</groupId>
                                    <artifactId>quarkus-extension-processor</artifactId>
                                    <version>3.21.4</version>
                                </path>
                            </annotationProcessorPaths>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
